language: java
sudo: required

notifications:
  email: false

jdk:
  - oraclejdk8

after_success:
  - ./gradlew jacocoTestReport
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

  - ./gradlew clean build javadoc sourcesJar uploadArchives -PnexusUsername="$NEXUS_USER_NAME" -PnexusPassword="$NEXUS_PASSWORD"